const DATA={
recallWords:[
 'ÁRBOL','AVIÓN','BICICLETA','BOTELLA','CAMISA','CAMPANA','CARTERA','CEBRA','CEPILLO','COCHE',
 'CUCHARA','ESCALERA','ESPEJO','ESTRELLA','FARO','FLOR','GATO','GUITARRA','HELADO','ISLA',
 'JARRA','JARDÍN','LLAVE','LIBRO','LUNA','MANZANA','MARIPOSA','MONTAÑA','NUBE','PAN',
 'PELOTA','PERRO','PLATO','PUERTA','QUESO','RELOJ','SILLA','SOMBRERO','TAMBOR','TELÉFONO',
 'TREN','VASO','VELA','VENTANA','ZAPATO','ZORRO','ALAMBRE','ALCACHOFA','ALMOHADA','ANCLA',
 'ANILLO','ARAÑA','ARENA','ARMARIO','ARROYO','ASIENTO','AZÚCAR','BAHÍA','BANDERA','BARCO',
 'BASTÓN','BATA','BELLOTA','BIGOTE','BLUSA','BOLSA','BOSQUE','BRAZO','BRÚJULA','BUFANDA',
 'BÚHO','BURBUJA','CABALLO','CABEZA','CAJA','CALCETÍN','CÁMARA','CAMINO','CANELA','CANOA',
 'CAPUCHA','CARACOL','CASTILLO','CEREZA','CHIMENEA','CÍRCULO','CIRUELA','CLAVO','COLLAR','COLUMPIO',
 'COMETA','CONEJO','CORONA','CORTINA','DADO','DELFIN','DIENTE','DINERO','DRAGÓN','DUCHA',
 'EDIFICIO','EMBUDO','ENCHUFE','ERIZO','ESCOBA','ESFERA','ESPUMA','FÁBRICA','FALDA','FAMILIA',
 'FLECHA','FLAUTA','FOCA','FOGATA','FUENTE','GALLETA','GALLINA','GAFAS','GANCHO','GARAJE',
 'GELATINA','GLOBO','GORRA','GRANJA','HADA','HAMACA','HARINA','HIERRO','HORMIGA','HOSPITAL',
 'HUELLA','IGLESIA','IGLÚ','IMÁN','JABÓN','JERSEY','JOYERO','JUGUETE','JUGO','LADRILLO',
 'LAGO','LÁPIZ','LEÓN','LIMÓN','LINTERNA','LOBO','MALETA','MARTILLO','MELÓN','MESA',
 'MOLINO','MOCHILA','MONEDA','MONO','MURAL','MUSEO','NARANJA','NIDO','NIEVE','OCÉANO',
 'OFICINA','OLA','ORUGA','OVEJA','PÁJARO','PALMERA','PAPEL','PARQUE','PATO','PAYASO',
 'PECERA','PEONZA','PIEDRA','PINGÜINO','PINTURA','PIRATA','PISCINA','PLANETA','PLUMA','POSTAL',
 'PRISMA','PUEBLO','RAMA','RANA','RATÓN','REGALO','REMO','RÍO','ROBOT','ROCA',
 'ROSA','RUEDA','SÁBANA','SALERO','SARTÉN','SEMILLA','SEÑAL','SERPIENTE','SOL','SOMBRILLA',
 'SOFÁ','SOBRE','TABLA','TAZA','TEATRO','TECHO','TENEDOR','TIJERA','TOMATE','TORRE',
 'TORTUGA','TRIGO','TÚNEL','UVAS','VACA','VELERO','VOLCÁN','YATE','ZUMO'
],
themes:{
 food:['🍎','🍐','🍊','🍋','🍉','🍇','🍓','🍑','🍍','🥝','🥑','🥕','🌽','🍕','🍔','🍣','🍦','🍩'],
 animals:['🐶','🐱','🐭','🐰','🦊','🐻','🐼','🐯','🦁','🐷','🐸','🐵','🐧','🦉','🐴','🦄','🐝','🐢','🐙','🐬'],
 objects:['⌚','📱','💻','📷','💡','🔦','📚','✏️','🔑','⚙️','🧭','⏰','🎁','🎈','🪑','🎸'],
 nature:['🌵','🌲','🌳','🌴','🍀','🍁','🍄','🌷','🌹','🌻','⭐','⚡','❄️','🌈','🔥','🌊'],
 symbols:['♠️','♥️','♦️','♣️','🔺','🔷','⬛','⬜','🟢','🟡','🟣','🔵','➕','➖','🔔','🎵']
},
words:[
 ['JARDIN','lugar donde crecen plantas'],['PUENTE','cruza un río'],['PLANETA','la Tierra es uno'],['COHETE','vuela al espacio'],
 ['VIOLIN','instrumento de cuerda'],['DESIERTO','muy seco'],['BIBLIOTECA','llena de libros'],['PRADERA','campo de hierba'],
 ['BRUJULA','indica el norte'],['MOTOR','da energía a una máquina'],['PIRAMIDE','monumento egipcio'],['VOLCAN','entra en erupción'],
 ['HORIZONTE','donde se unen cielo y tierra'],['LINTERNA','luz portátil'],['HUERTO','cultivo de frutas y verduras'],['COCINA','lugar para cocinar']
],
processes:[
 {name:'Preparar té con bolsita',steps:['Llenar el hervidor','Encender el hervidor','Poner una bolsita en la taza','Verter el agua ya hervida','Esperar el tiempo de reposo','Retirar la bolsita']},
 {name:'Cepillarse los dientes',steps:['Coger el cepillo','Mojar las cerdas','Añadir pasta de dientes','Cepillar los dientes','Enjuagarse la boca','Guardar el cepillo']},
 {name:'Poner una lavadora',steps:['Separar la ropa','Meter la ropa en el tambor','Añadir detergente','Cerrar la puerta','Elegir el programa','Pulsar inicio']},
 {name:'Preparar café de cápsula',steps:['Llenar el depósito de agua','Encender la cafetera','Esperar el aviso de lista','Abrir el compartimento','Colocar y cerrar la cápsula','Pulsar el botón de café']},
 {name:'Hacer una tortilla francesa',steps:['Romper los huevos en un cuenco','Batir los huevos','Encender la sartén con aceite','Verter los huevos batidos','Doblar la tortilla cuajada','Pasarla al plato']},
 {name:'Preparar una ensalada',steps:['Lavar las verduras','Secar las verduras lavadas','Cortar las verduras','Ponerlas en un bol','Añadir el aliño','Mezclar la ensalada']},
 {name:'Calentar comida en microondas',steps:['Poner la comida en un recipiente apto','Cubrir el recipiente','Introducirlo en el microondas','Elegir el tiempo','Pulsar inicio','Comprobar la temperatura']},
 {name:'Hacer una compra online',steps:['Buscar el producto','Abrir su ficha','Añadirlo a la cesta','Escribir la dirección','Elegir el pago','Confirmar la compra']},
 {name:'Enviar un paquete',steps:['Meter el objeto en una caja','Cerrar la caja','Pegar la etiqueta de dirección','Elegir el envío','Pagar el envío','Entregar el paquete']},
 {name:'Reservar una cita online',steps:['Elegir el servicio','Elegir el profesional','Seleccionar fecha y hora','Escribir los datos','Revisar la reserva','Pulsar confirmar']},
 {name:'Pedir comida a domicilio',steps:['Elegir el restaurante','Abrir su carta','Añadir los platos','Escribir la dirección','Elegir el pago','Confirmar el pedido']},
 {name:'Preparar una mochila de excursión',steps:['Abrir la mochila','Guardar la botella de agua','Guardar la comida','Añadir la ropa necesaria','Revisar el contenido','Cerrar la mochila']},
 {name:'Preparar una maleta',steps:['Abrir la maleta','Doblar la ropa','Guardar la ropa doblada','Añadir los objetos de aseo','Guardar los documentos','Cerrar la maleta']},
 {name:'Coger un avión con equipaje facturado',steps:['Mostrar la documentación','Facturar el equipaje','Pasar el control de seguridad','Llegar a la puerta de embarque','Subir al avión','Sentarse en el asiento']},
 {name:'Tomar un tren',steps:['Comprar o validar el billete','Leer el andén asignado','Ir al andén','Esperar la llegada del tren','Subir al tren','Buscar el asiento']},
 {name:'Acudir a una consulta médica',steps:['Pedir una cita','Llegar a la consulta','Explicar los síntomas','Responder a las preguntas','Escuchar las indicaciones','Recoger la receta']},
 {name:'Lavar los platos a mano',steps:['Retirar los restos de comida','Mojar la esponja','Añadir detergente a la esponja','Frotar los platos','Aclarar con agua','Dejar escurrir los platos']},
 {name:'Limpiar una mesa',steps:['Retirar los objetos','Doblar el paño','Humedecer el paño','Limpiar la superficie','Secar la superficie','Volver a colocar los objetos']},
 {name:'Ordenar un escritorio',steps:['Retirar los objetos de la mesa','Separar los papeles','Guardar los papeles archivados','Limpiar la superficie vacía','Colocar solo el material necesario']},
 {name:'Regar una planta en maceta',steps:['Tocar la tierra','Llenar la regadera','Regar la tierra','Esperar a que escurra','Vaciar el plato si sobra agua','Guardar la regadera']},
 {name:'Plantar una semilla',steps:['Llenar la maceta de tierra','Hacer un hueco en la tierra','Colocar la semilla','Cubrir el hueco','Regar suavemente','Poner la maceta en su lugar']},
 {name:'Cambiar una bombilla fría',steps:['Cortar la corriente','Quitar la bombilla antigua','Enroscar la bombilla nueva','Restablecer la corriente','Accionar el interruptor','Comprobar que se enciende']},
 {name:'Montar una estantería sencilla',steps:['Abrir la caja de piezas','Separar tornillos y tablas','Unir los laterales a la base','Colocar los estantes','Apretar todos los tornillos','Comprobar que no se mueve']},
 {name:'Preparar una videollamada',steps:['Abrir la aplicación','Crear la reunión','Copiar el enlace','Enviar el enlace','Comprobar cámara y micrófono','Unirse a la reunión']},
 {name:'Enviar un correo con adjunto',steps:['Abrir el correo','Crear un mensaje nuevo','Escribir el destinatario','Adjuntar el archivo','Redactar el mensaje','Pulsar enviar']},
 {name:'Imprimir un documento',steps:['Abrir el documento','Abrir el menú de impresión','Seleccionar la impresora','Elegir el número de copias','Confirmar la impresión','Recoger las hojas']},
 {name:'Guardar una copia de seguridad',steps:['Conectar el dispositivo de copia','Abrir la carpeta de destino','Elegir los archivos','Copiar los archivos','Esperar a que termine','Comprobar la copia']},
 {name:'Instalar una aplicación',steps:['Abrir la tienda de aplicaciones','Buscar la aplicación','Abrir la ficha correcta','Pulsar instalar','Esperar la descarga','Pulsar abrir']},
 {name:'Recuperar una contraseña',steps:['Abrir la página de acceso','Pulsar recuperar contraseña','Escribir el correo','Abrir el mensaje recibido','Crear la contraseña nueva','Iniciar sesión']},
 {name:'Preparar una presentación',steps:['Elegir el tema','Escribir el título','Crear el esquema','Añadir las diapositivas','Revisar las diapositivas','Guardar el archivo']},
 {name:'Repasar un tema para un examen',steps:['Abrir los apuntes del tema','Leer el resumen','Resolver los ejercicios','Corregir los ejercicios','Anotar los errores','Releer los errores anotados']},
 {name:'Empezar una sesión de ejercicio',steps:['Elegir la actividad','Ponerse ropa deportiva','Empezar el calentamiento','Realizar el ejercicio principal','Hacer estiramientos','Beber agua']},
 {name:'Usar un cajero para retirar efectivo',steps:['Introducir la tarjeta','Escribir el código','Elegir retirar efectivo','Indicar la cantidad','Confirmar la operación','Recoger tarjeta y dinero']},
 {name:'Devolver un libro en biblioteca',steps:['Llevar el libro a la biblioteca','Buscar el mostrador de devoluciones','Entregar el libro','Esperar el registro','Recoger el comprobante']},
 {name:'Cruzar una calle con semáforo',steps:['Llegar al paso de peatones','Pulsar el botón de peatones','Esperar la luz verde','Mirar a ambos lados','Empezar a cruzar']},
 {name:'Reciclar envases',steps:['Vaciar el envase','Separar la tapa si corresponde','Identificar el material','Elegir el contenedor','Depositar el envase']},
 {name:'Revisar un botiquín',steps:['Abrir el botiquín','Sacar los productos','Retirar los caducados','Añadir los productos necesarios','Cerrar el botiquín','Guardarlo en su lugar']},
 {name:'Organizar una merienda pequeña',steps:['Elegir la fecha','Hacer la lista de invitados','Enviar las invitaciones','Comprar la comida','Preparar la mesa','Recibir a los invitados']},
 {name:'Planificar una ruta en transporte público',steps:['Escribir el destino','Consultar las líneas disponibles','Elegir la línea','Consultar la hora de salida','Guardar la ruta elegida']},
 {name:'Configurar una alarma',steps:['Abrir la aplicación de reloj','Crear una alarma nueva','Elegir la hora','Elegir los días','Guardar la alarma','Comprobar que está activa']},
 {name:'Reparar un pinchazo con cámara',steps:['Desinflar por completo la rueda','Soltar la rueda de la bicicleta','Sacar la cámara de la cubierta','Reparar o sustituir la cámara','Montar de nuevo la rueda','Inflar hasta la presión indicada']}
],
odd:[
 {cat:['🍎','🍐','🍊','🍌','🍇','🍓'],outs:['🥕','🥦','🧀'],why:'frutas'},
 {cat:['🐶','🐱','🐰','🐴','🐷'],outs:['🦅','🐧','🐍'],why:'mamíferos'},
 {cat:['🚗','🚌','🚕','🚚','🚜'],outs:['✈️','🚁','⛵'],why:'vehículos de carretera'}
],
pal:['#e74c3c','#3498db','#2ecc71','#f1c40f','#9b59b6','#e67e22','#1abc9c','#e84393']
};
